import type {
  ConsentEvent,
  PrivacyRequest,
  PrivacyIncident,
  PersonalDataField,
  ProcessingActivity,
  Vendor,
} from "../types";

export const initialConsentEvents: ConsentEvent[] = [
  {
    id: "evt_con_881",
    timestamp: "2026-09-26T15:02:14+05:30",
    eventType: "consent_granted",
    visitorRef: "anon_sha256_8f3c7a1098b1e45f920d3a7c6e5b4a3f",
    categories: ["Necessary", "Analytics"],
    bannerVersion: "v2.1 (DPDP-Notice-2026.04)",
    policyVersion: "v3.4.1",
    property: "asterpay.in",
    ipHash: "hash_ip_e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    evidenceHash: "0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b",
  },
  {
    id: "evt_con_880",
    timestamp: "2026-09-26T14:58:33+05:30",
    eventType: "preference_changed",
    visitorRef: "anon_sha256_1d9e8c7b6a5f4e3d2c1b0a9f8e7d6c5b",
    categories: ["Necessary"],
    bannerVersion: "v2.1 (DPDP-Notice-2026.04)",
    policyVersion: "v3.4.1",
    property: "asterpay.in",
    ipHash: "hash_ip_8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
    evidenceHash: "1f2e3d4c5b6a7089123456789abcdef0123456789abcdef0123456789abcdef0",
  },
  {
    id: "evt_con_879",
    timestamp: "2026-09-26T14:41:09+05:30",
    eventType: "consent_denied",
    visitorRef: "anon_sha256_5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d",
    categories: ["Necessary"],
    bannerVersion: "v2.1 (DPDP-Notice-2026.04)",
    policyVersion: "v3.4.1",
    property: "asterpay.in",
    ipHash: "hash_ip_ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb",
    evidenceHash: "2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b",
  },
  {
    id: "evt_con_878",
    timestamp: "2026-09-26T14:30:22+05:30",
    eventType: "consent_withdrawn",
    visitorRef: "anon_sha256_9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f",
    categories: ["Necessary"],
    bannerVersion: "v2.0 (DPDP-Notice-2026.01)",
    policyVersion: "v3.4.0",
    property: "asterpay.in",
    ipHash: "hash_ip_4e07408562bedb8b60ce05c1decfe3ad16b72230967de01f640b7e4729b49fce",
    evidenceHash: "3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c",
  },
  {
    id: "evt_con_877",
    timestamp: "2026-09-26T14:15:45+05:30",
    eventType: "consent_granted",
    visitorRef: "anon_sha256_7b8a9c0d1e2f3a4b5c6d7e8f9a0b1c2d",
    categories: ["Necessary", "Analytics", "Advertising"],
    bannerVersion: "v2.1 (DPDP-Notice-2026.04)",
    policyVersion: "v3.4.1",
    property: "asterpay.in",
    ipHash: "hash_ip_4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a",
    evidenceHash: "4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d",
  },
];

export const initialRequests: PrivacyRequest[] = [
  {
    id: "PR-2026-081",
    type: "Delete my data",
    requesterRef: "vi****@gmail.com",
    status: "In Progress",
    owner: "Priya Sharma (DPO)",
    submittedAt: "2026-09-20T10:15:00+05:30",
    slaDeadline: "2026-09-28T10:15:00+05:30",
    daysRemaining: 2,
    verificationStatus: "Verified",
    tasks: [
      { id: "tsk_1", title: "Aadhaar / Mobile OTP Authentication", assignedTo: "Identity Gateway", completed: true, completedAt: "2026-09-20T10:20:00Z" },
      { id: "tsk_2", title: "Locate records across MySQL, DynamoDB, HubSpot", assignedTo: "Arjun Mehta", completed: true, completedAt: "2026-09-21T14:00:00Z" },
      { id: "tsk_3", title: "Check statutory retention requirements (RBI 5-yr financial records)", assignedTo: "Priya Sharma", completed: true, completedAt: "2026-09-22T09:30:00Z" },
      { id: "tsk_4", title: "Execute soft-delete & cryptographic erasure of marketing profile", assignedTo: "Dev Team", completed: false },
    ],
    notes: "Requester has an inactive wallet balance of INR 0. KYC data must be retained under PMLA Rule 9, but marketing and tracking profiles must be purged.",
    resolutionEvidenceHash: "8f9e0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f",
  },
  {
    id: "PR-2026-082",
    type: "Request a copy of my data",
    requesterRef: "ra****@outlook.com",
    status: "Assigned",
    owner: "Arjun Mehta",
    submittedAt: "2026-09-24T16:20:00+05:30",
    slaDeadline: "2026-10-04T16:20:00+05:30",
    daysRemaining: 8,
    verificationStatus: "Verified",
    tasks: [
      { id: "tsk_21", title: "Verify identity via registered mobile OTP", assignedTo: "Identity Gateway", completed: true, completedAt: "2026-09-24T16:25:00Z" },
      { id: "tsk_22", title: "Generate JSON archive of profile, ledger, and support tickets", assignedTo: "Data Ops", completed: false },
      { id: "tsk_23", title: "Encrypt payload with client public key and sign evidence pack", assignedTo: "Security", completed: false },
    ],
    notes: "Requested full export of transaction history and consent history.",
  },
  {
    id: "PR-2026-079",
    type: "Third-party/processor disclosure",
    requesterRef: "su****@yahoo.in",
    status: "Waiting",
    owner: "Priya Sharma",
    submittedAt: "2026-09-18T11:00:00+05:30",
    slaDeadline: "2026-09-28T11:00:00+05:30",
    daysRemaining: 2,
    verificationStatus: "Pending Document",
    tasks: [
      { id: "tsk_31", title: "Government Photo ID upload for verification", assignedTo: "Requester", completed: false },
    ],
    notes: "Waiting for government photo ID upload to verify identity before disclosing processor list.",
  },
  {
    id: "PR-2026-075",
    type: "Correct my data",
    requesterRef: "an****@asterpay.in",
    status: "Completed",
    owner: "Arjun Mehta",
    submittedAt: "2026-09-12T09:00:00+05:30",
    slaDeadline: "2026-09-22T09:00:00+05:30",
    daysRemaining: 0,
    verificationStatus: "Verified",
    tasks: [
      { id: "tsk_41", title: "Verify corrected address utility bill", assignedTo: "Operations", completed: true, completedAt: "2026-09-13T10:00:00Z" },
      { id: "tsk_42", title: "Update CRM & Billing engine records", assignedTo: "Arjun Mehta", completed: true, completedAt: "2026-09-14T15:00:00Z" },
      { id: "tsk_43", title: "Generate cryptographic resolution receipt", assignedTo: "System", completed: true, completedAt: "2026-09-14T15:05:00Z" },
    ],
    notes: "Residential address corrected in KYC records following verification of electricity bill.",
    resolutionEvidenceHash: "aa11bb22cc33dd44ee55ff6600112233445566778899aabbccddeeff00112233",
  },
];

export const initialIncidents: PrivacyIncident[] = [
  {
    id: "INC-2026-004",
    title: "Unauthorized public S3 bucket exposure containing settlement reports (Phone & PAN)",
    severity: "Critical",
    status: "Obligations Determined",
    detectedAt: "2026-09-25T18:00:00+05:30",
    leadInvestigator: "Priya Sharma (DPO) & CyberSec Team",
    affectedSystems: ["AWS S3 ap-south-1 Bucket 'asterpay-settlements-temp'", "ETL Archiver"],
    affectedDataCategories: ["Contact Info (Phone Numbers)", "Financial Identifiers (PAN, Bank Account Numbers)"],
    affectedPopulation: 14200,
    vendorInvolved: "Cloud Infrastructure (AWS Mumbai)",
    summary:
      "A misconfigured IAM policy during an ETL pipeline migration left an interim export bucket open to public read for 3 hours 12 minutes before automated containment. 14,200 merchant & customer records were present in the export slice.",
    evidenceHash: "a1b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef0",
    obligations: [
      {
        id: "ob_01",
        authority: "Affected Data Principals",
        requirement: "DPDP Act Section 8(6) & Rules 2026: Notice to each affected Data Principal 'without delay'",
        deadlineText: "Without delay upon risk assessment",
        deadlineIso: "2026-09-27T18:00:00+05:30",
        status: "In Preparation",
        actionRequired: "Approve communication template detailing nature of data, safety measures taken, and DPO helpline.",
      },
      {
        id: "ob_02",
        authority: "Data Protection Board of India (DPBI)",
        requirement: "DPDP Rules 2026 Rule 11: Mandatory 72-hour formal breach report to DPBI portal",
        deadlineText: "72 hours statutory clock (51h remaining)",
        deadlineIso: "2026-09-28T18:00:00+05:30",
        status: "In Preparation",
        statutoryClockHours: 72,
        hoursRemaining: 51,
        actionRequired: "Compile forensic report, containment timeline, root-cause fix, and DPO attestation.",
      },
      {
        id: "ob_03",
        authority: "CERT-In",
        requirement: "Cybersecurity Directions 2022: Reporting within 6 hours of incident confirmation",
        deadlineText: "Submitted within 6h",
        deadlineIso: "2026-09-25T23:59:00+05:30",
        status: "Submitted",
        actionRequired: "Acknowledgment received: Ticket CERTIN-2026-9921.",
      },
    ],
    timeline: [
      { time: "2026-09-25T18:00:00+05:30", event: "Incident detected via CloudTrail anomaly rule", actor: "Automated SIEM Sensor" },
      { time: "2026-09-25T18:14:00+05:30", event: "Bucket ACL blocked, access revoked, forensic snapshot created", actor: "SecOps Lead" },
      { time: "2026-09-25T19:30:00+05:30", event: "CERT-In initial 6-hour advisory report submitted", actor: "CISO" },
      { time: "2026-09-26T09:00:00+05:30", event: "Affected population bounded to 14,200 records", actor: "Priya Sharma" },
      { time: "2026-09-26T12:00:00+05:30", event: "DPBI draft response prepared for DPO review", actor: "Privacy Counsel" },
    ],
  },
];

export const initialPersonalDataFields: PersonalDataField[] = [
  {
    id: "fld_01",
    fieldName: "customer_phone",
    category: "Contact Information",
    sensitivity: "High",
    sourceRepo: "asterpay/core-checkout",
    sourceFile: "src/billing.ts",
    sourceLine: 42,
    confidence: 99,
    detectedAt: "2026-09-26T13:10:00+05:30",
    status: "Unmapped (AI Suggested)",
  },
  {
    id: "fld_02",
    fieldName: "customer_email",
    category: "Contact Information",
    sensitivity: "Medium",
    sourceRepo: "asterpay/core-checkout",
    sourceFile: "src/billing.ts",
    sourceLine: 48,
    confidence: 98,
    detectedAt: "2026-09-26T13:10:00+05:30",
    status: "Unmapped (AI Suggested)",
  },
  {
    id: "fld_03",
    fieldName: "pan_number",
    category: "Government Identifier",
    sensitivity: "High",
    sourceRepo: "asterpay/core-checkout",
    sourceFile: "src/models/user.ts",
    sourceLine: 18,
    confidence: 97,
    detectedAt: "2026-09-26T13:12:00+05:30",
    status: "Unmapped (AI Suggested)",
  },
  {
    id: "fld_04",
    fieldName: "dob",
    category: "Demographic / Age",
    sensitivity: "Medium",
    sourceRepo: "asterpay/core-checkout",
    sourceFile: "src/models/user.ts",
    sourceLine: 24,
    confidence: 95,
    detectedAt: "2026-09-26T13:12:00+05:30",
    status: "Unmapped (AI Suggested)",
  },
  {
    id: "fld_05",
    fieldName: "device_id",
    category: "Device Telemetry",
    sensitivity: "Normal",
    sourceRepo: "asterpay/frontend-web",
    sourceFile: "src/utils/telemetry.ts",
    sourceLine: 12,
    confidence: 92,
    detectedAt: "2026-09-20T10:00:00+05:30",
    mappedActivityId: "act_04",
    status: "Mapped",
  },
  {
    id: "fld_06",
    fieldName: "bank_account_number",
    category: "Financial Data",
    sensitivity: "High",
    sourceRepo: "asterpay/payouts-service",
    sourceFile: "src/services/settlement.ts",
    sourceLine: 89,
    confidence: 100,
    detectedAt: "2026-09-15T09:00:00+05:30",
    mappedActivityId: "act_02",
    status: "Mapped",
  },
];

export const initialProcessingActivities: ProcessingActivity[] = [
  {
    id: "act_01",
    name: "Customer Onboarding & KYC",
    purpose: "Verify customer and merchant identity under RBI Master Directions & DPDP compliance",
    legalBasis: "Legal Obligation",
    dataCategories: ["Government Identifier (PAN)", "Contact Info (Phone, Email)", "Date of Birth"],
    systems: ["asterpay-core-db", "kyc-verification-engine"],
    vendors: ["Razorpay", "Signzy KYC"],
    owner: "Kavita Rao (Head of Risk)",
    retentionPeriod: "5 years post account closure (PMLA compliance)",
    evidenceCount: 14,
    status: "Approved",
  },
  {
    id: "act_02",
    name: "Payment Settlement & UPI Processing",
    purpose: "Execute merchant settlement payouts, UPI intent transactions, and chargeback audits",
    legalBasis: "Certain Legitimate Uses (DPDP S.7)",
    dataCategories: ["Financial Data (Bank Acc, VPA)", "Transaction ID", "Payer Name"],
    systems: ["settlement-service", "payouts-db"],
    vendors: ["Razorpay", "NPCI UPI Gateway"],
    owner: "Nikhil Joshi (Payments Ops)",
    retentionPeriod: "8 years (Companies Act & RBI guidelines)",
    evidenceCount: 22,
    status: "Approved",
  },
  {
    id: "act_03",
    name: "Customer Support & Dispute Resolution",
    purpose: "Resolve transaction failure inquiries, chargebacks, and refund complaints",
    legalBasis: "Certain Legitimate Uses (DPDP S.7)",
    dataCategories: ["Contact Info (Phone, Email)", "Support Ticket Logs", "Transaction Ref"],
    systems: ["crm-support-hubspot", "freshdesk-internal"],
    vendors: ["HubSpot", "Intercom"],
    owner: "Ayesha Malik (Support Lead)",
    retentionPeriod: "3 years post dispute resolution",
    evidenceCount: 8,
    status: "Approved",
  },
  {
    id: "act_04",
    name: "Product Analytics & Funnel Optimization",
    purpose: "Measure website conversion drop-offs and feature engagement",
    legalBasis: "Consent",
    dataCategories: ["Device Telemetry", "IP Address (Hashed)", "Session Duration"],
    systems: ["analytics-segment", "google-analytics-4"],
    vendors: ["Google Analytics", "Segment"],
    owner: "Rohan Varma (Product Lead)",
    retentionPeriod: "14 months (Rolling purge)",
    evidenceCount: 11,
    status: "Under Review",
  },
];

export const initialVendors: Vendor[] = [
  {
    id: "ven_01",
    name: "Razorpay Software Pvt. Ltd.",
    category: "Payment Processor",
    country: "India (Bengaluru)",
    dpaStatus: "Signed & Current",
    crossBorderTransfer: "Compliant (Permitted Territory)",
    observedScripts: ["https://checkout.razorpay.com/v1/checkout.js"],
    dataCategoriesProcessed: ["Card Tokens", "UPI VPA", "Transaction Amount", "Payer Phone"],
    lastAuditDate: "2026-07-15",
    riskRating: "Low",
  },
  {
    id: "ven_02",
    name: "Segment (Twilio Inc.)",
    category: "Analytics",
    country: "United States / EU AWS",
    dpaStatus: "Signed & Current",
    crossBorderTransfer: "Compliant (Permitted Territory)",
    observedScripts: ["https://cdn.segment.com/analytics.js/v1/..."],
    dataCategoriesProcessed: ["Device Telemetry", "Pseudonymous Visitor ID", "Event Clickstreams"],
    lastAuditDate: "2026-08-20",
    riskRating: "Medium",
  },
  {
    id: "ven_03",
    name: "Google Analytics (Google LLC)",
    category: "Analytics",
    country: "United States",
    dpaStatus: "Signed & Current",
    crossBorderTransfer: "Compliant (Permitted Territory)",
    observedScripts: ["https://www.googletagmanager.com/gtag/js"],
    dataCategoriesProcessed: ["Aggregated Session Metrics", "Screen Resolutions", "Geo IP (Truncated)"],
    lastAuditDate: "2026-05-10",
    riskRating: "Low",
  },
  {
    id: "ven_04",
    name: "HubSpot Inc.",
    category: "CRM / Support",
    country: "United States",
    dpaStatus: "Under Review",
    crossBorderTransfer: "Compliant (Permitted Territory)",
    observedScripts: ["https://js.hs-scripts.com/..."],
    dataCategoriesProcessed: ["Lead Name", "Business Email", "Marketing Cookie ID"],
    lastAuditDate: "2026-03-12",
    riskRating: "Medium",
  },
];
